### ISSUE TITLE
[fill-in-the-blanks] Cloze (error) input lost after answering card  (Anki 2.1.55)

### ISSUE THREAD

**Issue by tommyplusdev** [ssricardo/anki-plugins#124]
Hello!

It seems that the cloze input is lost when answering on Anki 2.1.55 (new update). It works fine on 2.1.54.

For instance, please observe the following images (Anki 2.1.55):

![cloze_input_lost](https://user-images.githubusercontent.com/116316499/210960572-89008009-8e1b-440a-9cfa-5d3ac56e71b6.png)

![cloze_feedback](https://user-images.githubusercontent.com/116316499/210960583-f52fd611-ab45-4a4b-b365-75f6c781dca2.png)

Normally, it should display as such (Anki 2.1.54):

![cloze_error_success](https://user-images.githubusercontent.com/116316499/210960747-175e1c90-f198-440b-aeca-f4c5f1f67d1e.png)

Please let me know if this can be reproduced on your end. Thanks!

Edit: This might be the same bug as https://github.com/ssricardo/anki-plugins/issues/109

Low experience with Python / Anki add-on development here, unfortunately.

**Comment by ssricardo** [comment]
Hi, I could reproduce it.

Apparently something changed in Anki. I'm on it.

Thanks for reporting

**Comment by ssricardo** [comment]
Addressed in version 2.7 (10.01.2023)

**Comment by tommyplusdev** [comment]
I'm still having the same issue in 2.1.55/2.1.56.  Is there anything I could do to refresh the add-on? (already tried deleting and re-downloading the Add-on _after_ installing Anki 2.1.55 and Anki 2.1.56 respectively.

Edit: it seems this update also transmitted its effect to Anki 2.1.54 as well (prev version).
Edit 2: Found the issue; nesting the cloze within a div in the card editor loses cloze input. Re-opening new issue.
